"""FormBridge Discovery — recon to build a customer pack's selectors fast.

When the operator (or doctor) turns on Discovery on the real EHR, AitherConnect
reports, for that origin:
  * DOM fields  — every input/textarea/select: a stable selector, nearby label,
    type, and a sample value;
  * API fields  — flattened key-paths + samples scraped from the EHR's OWN
    fetch/XHR JSON responses (captured in the page's authenticated session) —
    the structured data behind the rendered page.

That inventory is mapped (field -> logical name) and turned into a draft
``source.fields`` for the mapping pack — turning "a developer with DevTools" into
"click through your screens once."

This store is TRANSIENT and in-memory (recon uses a DUMMY patient; nothing is
persisted) and every route is loopback-only — the inventory never leaves the box.
"""

from __future__ import annotations

import threading
import time


class DiscoveryStore:
    """Per-origin discovered field inventory. In-memory; cleared on restart."""

    def __init__(self) -> None:
        self._origins: dict[str, dict] = {}
        self._lock = threading.Lock()

    def ingest(self, origin: str, *, dom: list[dict] | None = None,
               api: list[dict] | None = None) -> dict:
        """Merge a discovery batch for *origin*. DOM keyed by selector, API by
        ``url + path`` — later samples replace earlier ones (most recent wins)."""
        origin = (origin or "").rstrip("/")
        if not origin:
            return {"dom": 0, "api": 0}
        with self._lock:
            entry = self._origins.setdefault(origin, {"dom": {}, "api": {}, "updated": 0.0})
            for f in dom or []:
                sel = str(f.get("selector") or "").strip()
                if sel:
                    entry["dom"][sel] = {
                        "selector": sel,
                        "label": str(f.get("label") or "")[:120],
                        "type": str(f.get("type") or ""),
                        "sample": str(f.get("sample") or "")[:200],
                    }
            for f in api or []:
                path = str(f.get("path") or "").strip()
                if path:
                    key = f"{f.get('url', '')}|{path}"
                    entry["api"][key] = {
                        "path": path,
                        "url": str(f.get("url") or "")[:200],
                        "sample": str(f.get("sample") or "")[:200],
                    }
            entry["updated"] = time.time()
            return {"dom": len(entry["dom"]), "api": len(entry["api"])}

    def get(self, origin: str | None = None) -> dict:
        with self._lock:
            if origin:
                origin = origin.rstrip("/")
                e = self._origins.get(origin)
                return {
                    "origin": origin,
                    "dom": sorted(e["dom"].values(), key=lambda x: x["selector"]) if e else [],
                    "api": sorted(e["api"].values(), key=lambda x: x["path"]) if e else [],
                }
            return {
                "origins": [
                    {"origin": o, "dom": len(e["dom"]), "api": len(e["api"]), "updated": e["updated"]}
                    for o, e in self._origins.items()
                ]
            }

    def clear(self, origin: str | None = None) -> None:
        with self._lock:
            if origin:
                self._origins.pop(origin.rstrip("/"), None)
            else:
                self._origins.clear()


def generate_source_fields(origin: str, mappings: dict[str, str]) -> str:
    """Turn {selector -> logical_name} into a draft mapping-pack ``source.fields``
    block the operator can paste into the customer's pack. Anchor + forms are
    still authored by hand; this nails the tedious selector→name part."""
    lines = [
        f"# Draft source.fields generated by FormBridge Discovery for {origin}",
        "source:",
        f'  origin: "{origin}"',
        "  anchor:",
        '    selector: "TODO — the patient-name element"',
        '    key_selector: "TODO — the patient-id element"',
        "  fields:",
    ]
    for selector, logical in sorted(mappings.items(), key=lambda kv: kv[1]):
        sel = str(selector).replace('"', '\\"')
        log = str(logical).strip()
        if log:
            lines.append(f'    - {{ capture: "{sel}", as: "{log}" }}')
    return "\n".join(lines) + "\n"


_store: DiscoveryStore | None = None
_store_lock = threading.Lock()


def get_discovery() -> DiscoveryStore:
    global _store
    with _store_lock:
        if _store is None:
            _store = DiscoveryStore()
        return _store
