"""Export & Publishing Tools — Output in multiple formats.

Manuscript, EPUB, SillyTavern character cards, Foundry VTT modules,
audiobook scripts, chapter art generation, book covers, and wiki export.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from adk.tools import tool

logger = logging.getLogger("saga.tools.publish")


def _get_engine():
    from .story_turn import _get_engine
    return _get_engine()


def _output_dir() -> Path:
    """Get or create output directory."""
    out = Path.home() / "Documents" / "saga-exports"
    out.mkdir(parents=True, exist_ok=True)
    return out


@tool(
    name="export_manuscript",
    description=(
        "Export the full story as a formatted manuscript with chapters, "
        "front matter, and page breaks."
    ),
)
def export_manuscript(
    title: str = "",
    author: str = "Saga",
    include_appendices: bool = True,
) -> dict:
    """Export as manuscript format.

    Args:
        title: Manuscript title (uses story name if empty)
        author: Author name
        include_appendices: Include character/location appendices
    """
    graph, memory, _ = _get_engine()
    from saga_engine.models import NodeType, MemoryType

    title = title or graph.world.story_name
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")

    lines = []
    lines.append(f"# {title}")
    lines.append(f"*by {author}*")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Story content from episodic memories in order
    episodes = sorted(
        [m for m in memory.get_all() if m.type == MemoryType.EPISODIC],
        key=lambda m: m.turn_number,
    )

    if episodes:
        lines.append("## Story")
        lines.append("")
        for ep in episodes:
            lines.append(f"**Turn {ep.turn_number}:** {ep.content}")
            lines.append("")

    if include_appendices:
        # Character appendix
        chars = graph.find_nodes_by_type(NodeType.CHARACTER)
        if chars:
            lines.append("---")
            lines.append("## Appendix A: Characters")
            lines.append("")
            for c in chars:
                lines.append(f"### {c.name}")
                lines.append(c.description)
                if c.properties.get("personality"):
                    lines.append(f"*Personality: {c.properties['personality']}*")
                lines.append("")

        # Location appendix
        locs = graph.find_nodes_by_type(NodeType.LOCATION)
        if locs:
            lines.append("## Appendix B: Locations")
            lines.append("")
            for loc in locs:
                lines.append(f"### {loc.name}")
                lines.append(loc.description)
                lines.append("")

        # Lore appendix
        lore = graph.find_nodes_by_type(NodeType.LORE)
        if lore:
            lines.append("## Appendix C: World Lore")
            lines.append("")
            for l in lore:
                lines.append(f"### {l.name}")
                lines.append(l.description)
                lines.append("")

    lines.append("---")
    lines.append(f"*Generated by Saga on {datetime.now().isoformat()}*")

    content = "\n".join(lines)
    output_path = _output_dir() / f"manuscript-{timestamp}.md"
    output_path.write_text(content, encoding="utf-8")

    return {
        "exported": str(output_path),
        "format": "manuscript",
        "title": title,
        "word_count": len(content.split()),
        "episodes": len(episodes),
    }


@tool(
    name="export_epub",
    description=(
        "Export as EPUB e-book format with metadata and table of contents. "
        "Generates an XHTML structure ready for EPUB packaging."
    ),
)
def export_epub(
    title: str = "",
    author: str = "Saga",
) -> dict:
    """Export as EPUB-ready XHTML.

    Args:
        title: Book title
        author: Author name
    """
    graph, memory, _ = _get_engine()
    from saga_engine.models import MemoryType

    title = title or graph.world.story_name
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")

    episodes = sorted(
        [m for m in memory.get_all() if m.type == MemoryType.EPISODIC],
        key=lambda m: m.turn_number,
    )

    # Build XHTML content
    xhtml = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE html>',
        '<html xmlns="http://www.w3.org/1999/xhtml">',
        '<head>',
        f'<title>{title}</title>',
        '<meta charset="utf-8"/>',
        '<style>body { font-family: Georgia, serif; margin: 2em; } '
        'h1 { text-align: center; } .chapter { page-break-before: always; }</style>',
        '</head>',
        '<body>',
        f'<h1>{title}</h1>',
        f'<p style="text-align:center"><em>by {author}</em></p>',
        '<hr/>',
    ]

    # Group episodes into chapters (~10 turns per chapter)
    chapter_size = 10
    for i in range(0, len(episodes), chapter_size):
        chapter_num = i // chapter_size + 1
        chapter_eps = episodes[i:i + chapter_size]
        xhtml.append(f'<div class="chapter">')
        xhtml.append(f'<h2>Chapter {chapter_num}</h2>')
        for ep in chapter_eps:
            xhtml.append(f'<p>{ep.content}</p>')
        xhtml.append('</div>')

    xhtml.extend(['</body>', '</html>'])

    content = "\n".join(xhtml)
    output_path = _output_dir() / f"epub-{timestamp}.xhtml"
    output_path.write_text(content, encoding="utf-8")

    return {
        "exported": str(output_path),
        "format": "epub_xhtml",
        "title": title,
        "chapters": (len(episodes) // 10) + 1,
        "note": "XHTML ready for EPUB packaging with calibre or pandoc",
    }


@tool(
    name="export_sillytavern",
    description=(
        "Export a character as a SillyTavern V2 character card (JSON). "
        "Compatible with SillyTavern, TavernAI, and other frontends."
    ),
)
def export_sillytavern(
    character_name: str,
    include_scenario: bool = True,
) -> dict:
    """Export as SillyTavern character card.

    Args:
        character_name: Character to export
        include_scenario: Include world context as scenario
    """
    graph, memory, _ = _get_engine()

    node = graph.find_node_by_name(character_name)
    if not node:
        return {"error": f"Character '{character_name}' not found"}

    props = node.properties
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")

    # Build character card
    card = {
        "spec": "chara_card_v2",
        "spec_version": "2.0",
        "data": {
            "name": node.name,
            "description": node.description,
            "personality": props.get("personality", ""),
            "scenario": graph.world.story_name if include_scenario else "",
            "first_mes": f"*{node.name} stands before you.*",
            "mes_example": "",
            "creator_notes": f"Exported from Saga - {graph.world.story_name}",
            "system_prompt": "",
            "post_history_instructions": "",
            "tags": node.tags,
            "creator": "Saga Storytelling Engine",
            "character_version": "1.0",
            "extensions": {
                "saga": {
                    "backstory": props.get("backstory", ""),
                    "appearance": props.get("appearance", ""),
                    "goals": props.get("goals", ""),
                    "fears": props.get("fears", ""),
                    "speech_style": props.get("speech_style", ""),
                },
            },
        },
    }

    content = json.dumps(card, indent=2)
    output_path = _output_dir() / f"sillytavern-{node.name.lower().replace(' ', '-')}-{timestamp}.json"
    output_path.write_text(content, encoding="utf-8")

    return {
        "exported": str(output_path),
        "format": "sillytavern_v2",
        "character": node.name,
    }


@tool(
    name="export_foundry",
    description=(
        "Export world data as a Foundry VTT journal module. "
        "Locations, NPCs, and items become journal entries."
    ),
)
def export_foundry() -> dict:
    """Export as Foundry VTT journal format."""
    graph, _, _ = _get_engine()
    from saga_engine.models import NodeType

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")

    entries = []

    for node in graph.get_all_nodes():
        entry = {
            "name": node.name,
            "type": node.type.value,
            "content": f"<h2>{node.name}</h2><p>{node.description}</p>",
            "folder": node.type.value.title(),
            "flags": {"saga": {"node_id": node.id, "status": node.status.value}},
        }
        if node.properties:
            props_html = "<ul>"
            for k, v in node.properties.items():
                if isinstance(v, str) and v:
                    props_html += f"<li><strong>{k}:</strong> {v}</li>"
            props_html += "</ul>"
            entry["content"] += props_html
        entries.append(entry)

    content = json.dumps({"name": graph.world.story_name, "entries": entries}, indent=2)
    output_path = _output_dir() / f"foundry-{timestamp}.json"
    output_path.write_text(content, encoding="utf-8")

    return {
        "exported": str(output_path),
        "format": "foundry_vtt",
        "entries": len(entries),
    }


@tool(
    name="export_audiobook_script",
    description=(
        "Export as an audiobook script with speaker tags and pacing notes "
        "formatted for TTS generation."
    ),
)
def export_audiobook_script() -> dict:
    """Export as audiobook TTS script."""
    graph, memory, _ = _get_engine()
    from saga_engine.models import MemoryType, NodeType

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")

    episodes = sorted(
        [m for m in memory.get_all() if m.type == MemoryType.EPISODIC],
        key=lambda m: m.turn_number,
    )

    characters = {c.name.lower(): c.name for c in graph.find_nodes_by_type(NodeType.CHARACTER)}

    lines = [f"# Audiobook Script: {graph.world.story_name}", ""]
    lines.append("## Speaker Tags")
    lines.append(f"- NARRATOR: Main narration voice")
    for name in characters.values():
        lines.append(f"- {name.upper()}: Character voice")
    lines.append("")

    lines.append("## Script")
    lines.append("")
    for ep in episodes:
        lines.append(f"### Turn {ep.turn_number}")
        lines.append(f"[NARRATOR] {ep.content}")
        lines.append("[PAUSE 1s]")
        lines.append("")

    content = "\n".join(lines)
    output_path = _output_dir() / f"audiobook-script-{timestamp}.md"
    output_path.write_text(content, encoding="utf-8")

    return {
        "exported": str(output_path),
        "format": "audiobook_script",
        "episodes": len(episodes),
        "speakers": len(characters) + 1,
    }


@tool(
    name="generate_chapter_art",
    description="Generate a description for chapter header illustration (for image generation).",
)
def generate_chapter_art(
    chapter_title: str,
    scene_description: str = "",
    art_style: str = "painterly",
) -> dict:
    """Generate art prompt for a chapter header.

    Args:
        chapter_title: Chapter title
        scene_description: Key scene to illustrate
        art_style: Art style (painterly, anime, realistic, sketch, watercolor)
    """
    graph, _, _ = _get_engine()

    return {
        "chapter": chapter_title,
        "scene": scene_description,
        "style": art_style,
        "world_mood": graph.world.mood,
        "instruction": (
            f"Generate a detailed image prompt for a {art_style} chapter header "
            f"illustration for '{chapter_title}'. Describe: composition, "
            f"key visual elements, lighting, mood, color palette. "
            f"Scene: {scene_description or 'derive from chapter title'}. "
            f"Format as a stable diffusion / ComfyUI prompt."
        ),
    }


@tool(
    name="generate_book_cover",
    description="Generate a description for book cover art from story metadata.",
)
def generate_book_cover(
    title: str = "",
    art_style: str = "painterly",
) -> dict:
    """Generate book cover art prompt.

    Args:
        title: Book title
        art_style: Art style
    """
    graph, _, _ = _get_engine()
    from saga_engine.models import NodeType

    title = title or graph.world.story_name
    chars = graph.find_nodes_by_type(NodeType.CHARACTER)
    locs = graph.find_nodes_by_type(NodeType.LOCATION)

    return {
        "title": title,
        "style": art_style,
        "main_characters": [
            {"name": c.name, "appearance": c.properties.get("appearance", "")}
            for c in chars[:3]
        ],
        "key_locations": [l.name for l in locs[:3]],
        "mood": graph.world.mood,
        "instruction": (
            f"Generate a book cover prompt for '{title}'. "
            f"Style: {art_style}. Include: title placement area, "
            f"central visual motif, color scheme matching the mood ({graph.world.mood}), "
            f"key character silhouettes or symbols. "
            f"Format as a stable diffusion / ComfyUI prompt."
        ),
    }


@tool(
    name="export_wiki",
    description="Export world data as a MediaWiki-formatted encyclopedia.",
)
def export_wiki() -> dict:
    """Export as MediaWiki format."""
    graph, memory, _ = _get_engine()
    from saga_engine.models import NodeType

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")

    lines = [f"= {graph.world.story_name} Wiki =", ""]

    # Group nodes by type
    for node_type in NodeType:
        nodes = graph.find_nodes_by_type(node_type)
        if not nodes:
            continue

        lines.append(f"== {node_type.value.title()}s ==")
        lines.append("")

        for node in nodes:
            lines.append(f"=== {node.name} ===")
            lines.append(f"''Type: {node.type.value} | Status: {node.status.value}''")
            lines.append("")
            lines.append(node.description)
            lines.append("")

            # Properties
            if node.properties:
                lines.append("{| class=\"wikitable\"")
                for k, v in node.properties.items():
                    if isinstance(v, str) and v:
                        lines.append(f"|-")
                        lines.append(f"! {k.title()}")
                        lines.append(f"| {v}")
                lines.append("|}")
                lines.append("")

            # Relationships
            neighbors = graph.get_neighbors(node.id)
            if neighbors:
                lines.append("'''Relationships:'''")
                for neighbor, edge in neighbors:
                    lines.append(f"* {edge.type.value} [[{neighbor.name}]]: {edge.label}")
                lines.append("")

    content = "\n".join(lines)
    output_path = _output_dir() / f"wiki-{timestamp}.wiki"
    output_path.write_text(content, encoding="utf-8")

    return {
        "exported": str(output_path),
        "format": "mediawiki",
        "entries": graph.node_count,
    }
